'top-level':
  - High court
  - Immigration
  - Probate
Crime:
  - Crime
  - Domestic violence
  - Forced marriage
Family:
  - Adoption
  - Children
  - Civil partnership
  - Divorce
'Money and Property':
  - Bankruptcy
  - Money claims
  - Repossession
'Work and Benefit':
  - Employment
  - Social security
